import "./ui/globals.css";
import { inter, oxanium } from "@/app/ui/fonts";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Informática | UFSM",
  description: "Generated by create next app"
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${oxanium.variable}`}>
        {children}
      </body>
    </html>
  );
}
